# Generated by Django 4.2.3 on 2023-07-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuario_password_venta_total_productocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
    ]
