# Generated by Django 4.2.3 on 2023-07-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_producto_categoria_delete_productocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_de_venta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor')], default='Vendedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_de_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], default='efectivo', max_length=20),
        ),
    ]
