# Generated by Django 4.2.3 on 2023-07-25 04:58

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_venta_numero_de_venta_alter_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(default=myapp.models.generar_id_venta, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_de_venta',
            field=models.IntegerField(default=myapp.models.generar_id_venta, unique=True),
        ),
        migrations.AlterField(
            model_name='ventasproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
