# Generated by Django 4.2.3 on 2023-07-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_producto_stock_alter_venta_id_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
