# Generated by Django 4.2.4 on 2023-08-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sumi_delete_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suministro',
            old_name='nombre',
            new_name='nombre_producto',
        ),
    ]
