# Generated by Django 4.2.4 on 2023-08-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_categoria_suministro_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
