# Generated by Django 4.2.4 on 2023-08-05 01:00

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_suministro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(default=myapp.models.generar_id_venta, primary_key=True, serialize=False),
        ),
    ]
