# Generated by Django 4.2.4 on 2023-08-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_venta_fecha_alter_venta_id_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
    ]
