# Generated by Django 4.2.4 on 2023-08-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_id_producto_devolucion_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productoventa'),
        ),
    ]
