# Generated by Django 4.2.4 on 2023-08-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_devolucion_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoventa',
            name='precio',
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto'),
        ),
    ]
