# Generated by Django 4.2.4 on 2023-08-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_productoventa_subtotal_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='subtotal_producto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
