# Generated by Django 4.2.4 on 2023-08-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_productoventa_subtotal_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
