# Generated by Django 4.2.4 on 2023-08-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_productoventa_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoventa',
            name='cantidad_producto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
