# Generated by Django 4.2.4 on 2023-08-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_productoventa_cantidad_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
