# Generated by Django 4.2.4 on 2023-08-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_devolucion_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sumi',
        ),
    ]
