# Generated by Django 4.2.4 on 2023-08-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_delete_sumi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productoventa'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.venta'),
        ),
    ]
