# Generated by Django 4.2.4 on 2023-08-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_devolucion_producto_alter_devolucion_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='cantidad',
        ),
    ]
