# Generated by Django 4.2.4 on 2023-08-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_devolucion_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
