# Generated by Django 4.2.4 on 2023-08-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usuario',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
    ]
