# Generated by Django 4.2.4 on 2023-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_userprofile_usuario_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
