# Generated by Django 4.2.4 on 2023-08-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_delete_usuario_remove_userprofile_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
