# Generated by Django 4.2.4 on 2023-08-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
