# Generated by Django 4.2.4 on 2023-08-15 02:51

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_venta_id_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(default=myapp.models.generar_id_venta, primary_key=True, serialize=False),
        ),
    ]
