# Generated by Django 4.2.4 on 2023-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_venta_id_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_de_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], default='efectivo', max_length=15),
        ),
    ]
