# Generated by Django 4.2.4 on 2023-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_remove_producto_categoria_alter_producto_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='comentarios',
            field=models.CharField(max_length=50),
        ),
    ]
