# Generated by Django 4.2.4 on 2023-11-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_devolucion_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=15),
        ),
    ]
