# Generated by Django 4.2.4 on 2023-11-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_venta_metodo_de_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('numero_de_telefono', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('monto_de_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clase', models.CharField(choices=[('A', 'Cliente con descuentos'), ('B', 'Cliente con precios diferenciales')], max_length=1)),
            ],
        ),
    ]
